[default]
contracts = 'contracts'       # The contract directory
test = 'tests'                # The test directory
libs = ['modules']            # A list of library directories
solc_version = '0.8.7'        # Override for the solc version (setting this ignores `auto_detect_solc`)
offline = true                # Disable downloading of missing solc versions
optimizer = true              # Enable or disable the solc optimizer
optimizer_runs = 200          # The number of optimizer runs
verbosity = 3                 # The verbosity of tests
block_timestamp = 1649101835  # Timestamp for tests (Monday, April 4, 2022 3:50:35 PM EST)
block_number = 14521487       # Block number for tests
fuzz_runs = 1000              # Number of fuzz runs

# caches storage retrieved locally for certain chains and endpoints
# can also be restrictied to `chains = ["optimism", "mainnet"]`
# by default all endpoints will be cached, alternative options are "remote" for only caching non localhost endpoints and "<regex>"
# to disable storage caching entirely set `no_storage_caching = true`
rpc_storage_caching = { chains = ["mainnet"], endpoints = "all" }
# # this overrides `rpc_storage_caching` entirely
# no_storage_caching = false
# don't include the metadata hash, to allow for deterministic code: https://docs.soliditylang.org/en/latest/metadata.html, solc's default is "ipfs"
bytecode_hash = "none"

[shallow]
fuzz_runs = 1000

[deep]
fuzz_runs = 50000
